export const SITE_NAME = 'Paymitra';

export const NAV_LINKS = [
  { name: 'Home', href: '/' },
  { name: 'Shop', href: '/shop' },
  { name: 'Categories', href: '/categories' },
  { name: 'About', href: '/about' },
  { name: 'Contact', href: '/contact' },
];

export const FEATURED_CATEGORIES = [
  { id: 1, name: 'Electronics', slug: 'electronics', image: 'https://images.pexels.com/photos/1057313/pexels-photo-1057313.jpeg?auto=compress&cs=tinysrgb&w=600' },
  { id: 2, name: 'Fashion', slug: 'fashion', image: 'https://images.pexels.com/photos/934070/pexels-photo-934070.jpeg?auto=compress&cs=tinysrgb&w=600' },
  { id: 3, name: 'Home & Kitchen', slug: 'home-kitchen', image: 'https://images.pexels.com/photos/1358900/pexels-photo-1358900.jpeg?auto=compress&cs=tinysrgb&w=600' },
  { id: 4, name: 'Beauty & Personal Care', slug: 'beauty-personal-care', image: 'https://images.pexels.com/photos/4041392/pexels-photo-4041392.jpeg?auto=compress&cs=tinysrgb&w=600' },
];

export const FEATURED_PRODUCTS = [
  {
    id: 1,
    name: 'Wireless Bluetooth Earbuds',
    price: 89.99,
    discountPrice: 69.99,
    rating: 4.5,
    image: 'https://images.pexels.com/photos/3780681/pexels-photo-3780681.jpeg?auto=compress&cs=tinysrgb&w=600',
    category: 'Electronics',
    vendor: 'TechStar Electronics',
    isFeatured: true,
    isNew: true,
  },
  {
    id: 2,
    name: 'Luxury Leather Wallet',
    price: 59.99,
    discountPrice: null,
    rating: 4.3,
    image: 'https://images.pexels.com/photos/2079249/pexels-photo-2079249.jpeg?auto=compress&cs=tinysrgb&w=600',
    category: 'Fashion',
    vendor: 'Fashion World',
    isFeatured: true,
    isNew: false,
  },
  {
    id: 3,
    name: 'Smart Digital Watch',
    price: 129.99,
    discountPrice: 99.99,
    rating: 4.7,
    image: 'https://images.pexels.com/photos/437037/pexels-photo-437037.jpeg?auto=compress&cs=tinysrgb&w=600',
    category: 'Electronics',
    vendor: 'Gadget Zone',
    isFeatured: true,
    isNew: true,
  },
  {
    id: 4,
    name: 'Premium Coffee Maker',
    price: 199.99,
    discountPrice: 159.99,
    rating: 4.8,
    image: 'https://images.pexels.com/photos/585753/pexels-photo-585753.jpeg?auto=compress&cs=tinysrgb&w=600',
    category: 'Home & Kitchen',
    vendor: 'HomeLiving',
    isFeatured: true,
    isNew: false,
  },
  {
    id: 5,
    name: 'Natural Face Serum',
    price: 45.99,
    discountPrice: null,
    rating: 4.6,
    image: 'https://images.pexels.com/photos/5069438/pexels-photo-5069438.jpeg?auto=compress&cs=tinysrgb&w=600',
    category: 'Beauty & Personal Care',
    vendor: 'Organic Beauty',
    isFeatured: true,
    isNew: true,
  },
  {
    id: 6,
    name: 'Designer Sunglasses',
    price: 79.99,
    discountPrice: 59.99,
    rating: 4.4,
    image: 'https://images.pexels.com/photos/701877/pexels-photo-701877.jpeg?auto=compress&cs=tinysrgb&w=600',
    category: 'Fashion',
    vendor: 'Style Icons',
    isFeatured: true,
    isNew: false,
  },
  {
    id: 7,
    name: 'Portable Bluetooth Speaker',
    price: 69.99,
    discountPrice: 49.99,
    rating: 4.2,
    image: 'https://images.pexels.com/photos/1279107/pexels-photo-1279107.jpeg?auto=compress&cs=tinysrgb&w=600',
    category: 'Electronics',
    vendor: 'Sound Masters',
    isFeatured: true,
    isNew: true,
  },
  {
    id: 8,
    name: 'Stainless Steel Cookware Set',
    price: 249.99,
    discountPrice: 199.99,
    rating: 4.7,
    image: 'https://images.pexels.com/photos/8105035/pexels-photo-8105035.jpeg?auto=compress&cs=tinysrgb&w=600',
    category: 'Home & Kitchen',
    vendor: 'Culinary Experts',
    isFeatured: true,
    isNew: false,
  },
];

export const TESTIMONIALS = [
  {
    id: 1,
    name: 'John Smith',
    role: 'Customer',
    image: 'https://images.pexels.com/photos/3763188/pexels-photo-3763188.jpeg?auto=compress&cs=tinysrgb&w=600',
    comment: 'Paymitra has completely transformed how I shop online. Their customer service is exceptional and the product quality is always top-notch.',
  },
  {
    id: 2,
    name: 'Priya Sharma',
    role: 'Vendor',
    image: 'https://images.pexels.com/photos/1065084/pexels-photo-1065084.jpeg?auto=compress&cs=tinysrgb&w=600',
    comment: 'As a vendor, Paymitra has helped me expand my business reach. Their platform is user-friendly and the support team is always available to help.',
  },
  {
    id: 3,
    name: 'Michael Chen',
    role: 'Customer',
    image: 'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=600',
    comment: 'I love the variety of products available on Paymitra. The shipping is fast and returns are hassle-free. Definitely my go-to for online shopping.',
  },
];

export const FOOTER_LINKS = {
  company: [
    { name: 'About Us', href: '/about' },
    { name: 'Careers', href: '/careers' },
    { name: 'Press', href: '/press' },
    { name: 'Blog', href: '/blog' },
  ],
  support: [
    { name: 'Contact Us', href: '/contact' },
    { name: 'FAQs', href: '/faqs' },
    { name: 'Shipping & Returns', href: '/shipping-returns' },
    { name: 'Track Order', href: '/track-order' },
  ],
  legal: [
    { name: 'Terms of Service', href: '/terms' },
    { name: 'Privacy Policy', href: '/privacy' },
    { name: 'Cookie Policy', href: '/cookies' },
  ],
  forVendors: [
    { name: 'Become a Vendor', href: '/vendor/register' },
    { name: 'Vendor Login', href: '/vendor/login' },
    { name: 'Vendor Guidelines', href: '/vendor/guidelines' },
  ],
};